### PR TITLE
searcher.py: If release year is zero, handle it and show a list of mo…

### PR DESCRIPTION
**Pull request by sanjeevstunner**
…vies matching the title, and the user can manually chose which title to add to the watchlist

### CODE REVIEW

**Comment by sanjeevstunner** [comment]
This fixes the issue #51

**Comment by sanjeevstunner** [comment]
Test Results 

| Before | After |
| -------- | ------- |
| image | image
 |

**Comment by sanjeevstunner** [comment]
@lukearran wen merge this?

**Comment by lukearran** [comment]
> @lukearran wen merge this?

Sorry for the late review. Good catch, thanks for contributing!

**Comment by AdClarky** [comment]
I did address this in my recent PR [here](https://github.com/lukearran/TvTimeToTrakt/blob/a45a541f382d6d86bd5023795b2fdca079da5811/searcher.py#L146). Unsure which is a better fix but probably not best to have both. The try except fix may fix future issues so may be better.

**Comment by lukearran** [comment]
Ah yes, I see what you mean, @AdClarky. I'll revert this change to avoid duplication.

**Pull request merged**
